name: my-ci-flow
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Selenium Server HUB
        run: nohup java -jar selenium-server-4.17.0.jar hub & sleep 10
        shell: bash

      - name: Start Selenium Server nodes
        run: nohup java -jar selenium-server.jar node --port 5555 --selenium-manager true & sleep 10
        shell: bash

      - name: Setup ChromeDriver
        uses: browser-actions/setup-chrome@latest

      - name: Setup FirefoxDriver
        uses: browser-actions/setup-firefox@latest


      - name: Print working directory
        run: pwd

      - name: Run tests with pytest and generate report
        continue-on-error: true
        run: |
            python -m pytest  tests\\tests_runner.py --html=report_api.html --self-contained-html          


      - name: Upload Test Report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test-Reports
          path: ./*.html



