name: my-ci-flow
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup ChromeDriver
        uses: browser-actions/setup-chrome@latest

      - name: Setup FirefoxDriver
        uses: browser-actions/setup-firefox@latest

      - name: List all files in the repository
        run: find .

      - name: Print working directory
        run: pwd

      - name: Run tests with pytest and generate report
        continue-on-error: true
        run: |
            python -m pytest  W3Schools_project_final/W3Schools_project_final/tests/tests_runner.py --html=report_api.html --self-contained-html          


      - name: Upload Test Report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test-Reports
          path: ./*.html



