name: my-ci-flow
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup ChromeDriver
        uses: browser-actions/setup-chrome@latest
      - name: Setup FirefoxDriver
        uses: browser-actions/setup-firefox@latest
      - name: Run tests with pytest and generate report
        continue-on-error: true
        run: |
            pytest  tests/test_api/api_test_runner.py --html=report_api.html --self-contained-html          

      - name: Run API test_articles.py
        env:
          MY_TOKEN: ${{ secrets.SECRET_TOKEN }}
        run: |
          echo "Using secret token $SECRET_TOKEN"
          python tests/api_tests/test_goals.py



      - name: Upload Test Report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test-Reports
          path: ./*.html


      - name: slack - GitHub Actions Slack integration
        uses: act10ns/slack@v2.0.0
        with:
          status: in progress
        if: always()
        env:
          SLACK_CHANNEL: 'C06Q6FRSFKJ'
          SLACK_COLOR: 'good'
          SLACK_MESSAGE: 'Test Succeeded: ${{ github.run_id }}'
          SLACK_TITLE: 'Test Execution Succeeded'
          SLACK_USERNAME: 'GitHub Actions'
          SLACK_WEBHOOK: 'https://hooks.slack.com/services/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'
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

      - name: Notify Slack on failure
        uses: act10ns/slack@v2.0.0
        if: failure()
        env:
          SLACK_CHANNEL: 'C06Q6FRSFKJ'
          SLACK_COLOR: 'danger'
          SLACK_MESSAGE: 'Test Failed: ${{ github.run_id }}'
          SLACK_TITLE: 'Test Execution Failed'
          SLACK_USERNAME: 'GitHub Actions'
          SLACK_WEBHOOK: 'https://hooks.slack.com/services/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'
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK