name: my-ci-flow
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup ChromeDriver
        uses: browser-actions/setup-chrome@latest

      - name: Setup FirefoxDriver
        uses: browser-actions/setup-firefox@latest

      - name: List tests directory
        run: ls -l tests/
        working-directory: ${{ github.workspace }}

      - name: Print working directory
        run: pwd
        working-directory: ${{ github.workspace }}

      - name: Run tests with pytest and generate report
        continue-on-error: true
        run: |
          python -m pytest tests/tests_runner.py --html=report_api.html --self-contained-html
        working-directory: ${{ github.workspace }}

      - name: Upload Test Report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test-Reports
          path: ./*.html
        working-directory: ${{ github.workspace }}
